resources:  
  - name: code  
    type: git  
    source:  
      uri: https://github.com/rajkamalhm/concourse.git
      branch: master

jobs:
  - name: check file input
    plan:
    - get: code
      trigger: true
    - task: some task
      file: code/temp-pipe.yml
